/*
 * gen-catalog.ts — writes src/catalog/catalog.generated.ts from the folders in src/viz.
 * Run: `npm run gen:catalog` (predev / prebuild run it for you).
 *
 * Why generated: adding a visualization must be "create a folder", with no hand-edited registry.
 * Why not import.meta.glob: the SSR smoke and the checks run under tsx, outside Vite.
 * The output is committed (tsc needs it); `npm run check:catalog` fails when it is stale.
 * CHANGED (S3-lz): the shell gets the card fields as literals (VIZ_CARDS, evaluated here from each meta.ts) and
 * the full manifests only behind lazy loaders (VIZ_META_LOADERS) — no meta.ts is imported eagerly any more.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { toCard } from '../src/catalog/types';
import type { VizMeta } from '../src/catalog/types';
import { GENERATED_PATH, listVizFolders } from './lib/viz-folders';

const BANNER = `// AUTO-GENERATED by scripts/gen-catalog.ts — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:catalog\` (predev/prebuild do it for you); \`npm run check:catalog\`
// fails the build when this file is stale. Source of truth: src/viz/<id>/meta.ts.`;

// Folder names are validated kebab-case (lib/viz-folders.ts), so single quotes are always safe.
const lit = (v: string): string => {
  if (!/^[a-z0-9./-]+$/.test(v)) throw new Error(`Unsafe path in generated code: ${v}`);
  return `'${v}'`;
};

// CHANGED (S3-lz): the card data goes into the initial chunk — check:catalog keeps its average per entry within this
// budget (the 18 cards of 2026-10-07 average 265 B gzip; with their descriptions they would average ≈ 1.3 kB).
export const CARD_BUDGET_GZIP = 400;

// CHANGED (S3-lz): async — each meta.ts is evaluated to write its card fields.
export async function generate(): Promise<{ path: string; source: string; count: number; cardsGzip: number }> {
  const folders = listVizFolders();
  const cards: string[] = [];
  for (const f of folders) {
    const mod = (await import(pathToFileURL(join(f.dir, 'meta.ts')).href)) as { default?: VizMeta };
    const meta = mod.default;
    if (!meta || typeof meta !== 'object') throw new Error(`src/viz/${f.id}/meta.ts: no default export`);
    if (meta.id !== f.id) throw new Error(`src/viz/${f.id}/meta.ts: id '${meta.id}' must equal the folder name`);
    // JSON is a valid TS literal; string escaping is JSON.stringify's, so manifest text cannot break the file.
    cards.push(`  ${JSON.stringify(toCard(meta), null, 2).replace(/\n/g, '\n  ')},`);
  }
  const loaders = folders.map((f) => `  ${lit(f.id)}: () => import(${lit(`../viz/${f.id}/index`)}),`);
  const metaLoaders = folders.map((f) => `  ${lit(f.id)}: () => import(${lit(`../viz/${f.id}/meta`)}),`);

  const source = [
    BANNER,
    `import type { ComponentType } from 'react';`,
    `import type { VizBodyProps, VizCard, VizMeta } from './types';`,
    '',
    `export type VizLoader = () => Promise<{ default: ComponentType<VizBodyProps> }>;`,
    `export type VizMetaLoader = () => Promise<{ default: VizMeta }>;`,
    '',
    `export const VIZ_CARDS: readonly VizCard[] = [`,
    ...cards,
    `];`,
    '',
    `export const VIZ_LOADERS: Readonly<Record<string, VizLoader>> = {`,
    ...loaders,
    `};`,
    '',
    `export const VIZ_META_LOADERS: Readonly<Record<string, VizMetaLoader>> = {`,
    ...metaLoaders,
    `};`,
    '',
  ].join('\n');

  const cardsGzip = gzipSync(cards.join('\n'), { level: 9 }).length;
  return { path: GENERATED_PATH, source, count: folders.length, cardsGzip };
}

export function readGenerated(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

async function main(): Promise<void> {
  const { path, source, count } = await generate();
  if (readGenerated(path) === source) {
    console.log('✓ gen:catalog — up to date.');
    return;
  }
  writeFileSync(path, source);
  console.log(`✓ gen:catalog — wrote src/catalog/catalog.generated.ts (${count} visualization(s)).`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
