/*
 * gen-catalog.ts — writes src/catalog/catalog.generated.ts from the folders in src/viz.
 * Run: `npm run gen:catalog` (predev / prebuild run it for you).
 *
 * Why generated: adding a visualization must be "create a folder", with no hand-edited registry.
 * Why not import.meta.glob: the SSR smoke and the checks run under tsx, outside Vite.
 * The output is committed (tsc needs it); `npm run check:catalog` fails when it is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { GENERATED_PATH, listVizFolders } from './lib/viz-folders';

const BANNER = `// AUTO-GENERATED by scripts/gen-catalog.ts — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:catalog\` (predev/prebuild do it for you); \`npm run check:catalog\`
// fails the build when this file is stale. Source of truth: src/viz/<id>/meta.ts.`;

// Folder names are validated kebab-case (lib/viz-folders.ts), so single quotes are always safe.
const lit = (v: string): string => {
  if (!/^[a-z0-9./-]+$/.test(v)) throw new Error(`Unsafe path in generated code: ${v}`);
  return `'${v}'`;
};

export function generate(): { path: string; source: string } {
  const folders = listVizFolders();
  const imports = folders.map((f, i) => `import meta${i} from ${lit(`../viz/${f.id}/meta`)};`);
  const metas = folders.map((_, i) => `  meta${i},`);
  const loaders = folders.map((f) => `  ${lit(f.id)}: () => import(${lit(`../viz/${f.id}/index`)}),`);

  const source = [
    BANNER,
    `import type { ComponentType } from 'react';`,
    `import type { VizBodyProps, VizMeta } from './types';`,
    ...imports,
    '',
    `export type VizLoader = () => Promise<{ default: ComponentType<VizBodyProps> }>;`,
    '',
    `export const VIZ_METAS: readonly VizMeta[] = [`,
    ...metas,
    `];`,
    '',
    `export const VIZ_LOADERS: Readonly<Record<string, VizLoader>> = {`,
    ...loaders,
    `};`,
    '',
  ].join('\n');

  return { path: GENERATED_PATH, source };
}

export function readGenerated(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

function main(): void {
  const { path, source } = generate();
  if (readGenerated(path) === source) {
    console.log('✓ gen:catalog — up to date.');
    return;
  }
  writeFileSync(path, source);
  const count = (source.match(/^import meta\d+/gm) ?? []).length;
  console.log(`✓ gen:catalog — wrote src/catalog/catalog.generated.ts (${count} visualization(s)).`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
